// Greek God Workout Program — Dream Body Club
// แยกเป็น Gym Edition และ Home Edition ต่อวัน — ครบ 7 วัน

export const WORKOUT_PROGRAM = {
  day1: {
    title: "Day 1: Pull",
    emoji: "🔙",
    color: "#10AC84",
    gym: [
      { name: "V-Grip Lat Pulldown", note: "เอนหลังเล็กน้อย แอ่นอก วางเท้าให้มั่น", sets: "Feel 20, Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Bar Lat Pulldown", note: "จับบาร์กว้างกว่าหัวไหล่ เอนหลังเล็กน้อย", sets: "Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Single Lat Row (Cable/Machine)", note: "เล่นทีละข้าง มือดึงจาก เอียงตัว หุบแขน", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Preacher Curl หรือ Spider Curl", note: "ลอคหน้าลำตัว ออกแรงจากกล้ามแขน", sets: "Feel 20, Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Seated Dumbbell Curl หรือ Drag Curl", note: "ลอคหลังตรง ล็อคศอก", sets: "Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail/Drop 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Abs Crunch Cable/Machine", note: "ใช้ V-bar หันหน้าเข้าเครื่อง", sets: "Feel 20, Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Leg Raise", note: "ห้อยตัว", sets: "15 reps x 5 sets", rest: "พักเซตละ 1 นาที" },
    ],
    home: [
      { name: "V-Grip Band Pulldown", note: "ใช้ยางยืดแทนเครื่อง วางท่าให้มั่น", sets: "Feel 20, Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Band Lat Pulldown", note: "ยืนยึดยางไว้กับจุดสูง", sets: "Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Single Band Lat Row", note: "เล่นทีละข้าง ยืนถีบยาง", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Spider Curl หรือ Standing Curl", note: "ถอกหน้าลำตัว ออกแรงจากกล้ามแขน", sets: "Feel 20, Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Seated Dumbbell Curl หรือ Hammer Curl", note: "ลอคหลังตรง", sets: "Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail/Drop 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Abs Crunch Cable/Machine", note: "ใช้ V-bar หันหน้าเข้าเครื่อง", sets: "Feel 20, Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Leg Raise", note: "ห้อยตัว", sets: "15 reps x 5 sets", rest: "พักเซตละ 1 นาที" },
    ],
  },
  day2: {
    title: "Day 2: Push",
    emoji: "💪",
    color: "#FF9F43",
    gym: [
      { name: "Incline Smith Machine Press", note: "ม้านั่ง 30-40 องศา บาร์ตำแหน่งแตะอก", sets: "Feel 20, Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Seated Upper Chest Fly", note: "เคเบิลความสูงเท่าหัว เอนตัวด้านหน้า", sets: "Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Flat Smith Press", note: "บาร์ตำแหน่งแตะอกล่าง วางเท้าให้มั่น", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Super Set: Reverse + Bar Extension", note: "เล่น 2 ข้างพร้อมกัน", sets: "Feel 20, Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 12 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Overhead Extension", note: "ใช้เชือกหรือบาร์ ล็อคศอกนิ่ง", sets: "Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail/Drop 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Lateral Raise", note: "เล่นเบา โฟกัสยกศอกขึ้นมาบนไหล่ข้าง", sets: "Feel 20, Warm Kg 20, Fail/Drop ครั้ง", rest: "พัก 2 นาที" },
      { name: "Cable Rear Delt Fly", note: "นั่งหรือยืนก็ได้ ลากศอกออกด้านนอก", sets: "Warm Kg 20, Fail/Drop ครั้ง", rest: "พักเซตละ 1 นาที" },
    ],
    home: [
      { name: "Incline Dumbbell Press", note: "วางมือกว้างกว่าหัวไหล่ จังหวะลง", sets: "วอร์ม เหลือแรง 50%, เซ็ต 1-4 เหลือแรง 2/1.5/1/0.5", rest: "พัก 3 นาที" },
      { name: "Flat Dumbbell Press", note: "วางมือกว้างกว่าไหล่ มือคู่ตรง", sets: "วอร์ม เหลือแรง 50%, เซ็ต 1-4 เหลือแรง 2/1.5/1/0.5", rest: "พัก 3 นาที" },
      { name: "วิดพื้นอกล่าง", note: "วางมือแคบกว่าไหล่ หุบศอกเข้าอกกลาง", sets: "วอร์ม เหลือแรง 50%, เซ็ต 1-5 เหลือแรง 2/1.5/1/0.5/ถดถนหมดแรง", rest: "พัก 3 นาที" },
      { name: "Super Set: Skull Crusher + Kickback", note: "นอนกับม้าได้ไม่มีเบาะ", sets: "Feel 20, Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Dumbbell Overhead Extension", note: "ล็อคศอกนิ่ง ลงสุดดึงแขนและขาเตยเชป", sets: "Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail/Drop 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Lateral Raise", note: "เล่นเบา โฟกัสยกศอกขึ้นมาบนไหล่ข้าง", sets: "Feel 20, Warm Kg 20, Fail/Drop ครั้ง", rest: "พัก 2 นาที" },
      { name: "Dumbbell Rear Delt Fly", note: "นั่งหรือยืนก็ได้ ลากศอกออกด้านนอก", sets: "Warm Kg 20, Fail/Drop ครั้ง", rest: "พักเซตละ 1 นาที" },
    ],
  },
  day3: {
    title: "Day 3: Leg",
    emoji: "🦵",
    color: "#5F27CD",
    gym: [
      { name: "Smith Shoulder Press", note: "เบาะ 80 องศา เอาศอกมาหน้าลำตัวนิดนึง", sets: "Feel 20, Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Rope Front Raise", note: "แขวนได้นิดหน่อย โฟกัสลากศอกไปด้านหน้า", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Smith Machine Squat", note: "ก้าวเท้าไป 1 ก้าวจากจุดยืนปกติ", sets: "Feel 20, Warm 12, Work 2RIR/1.5RIR/1RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Leg Press", note: "ความกว้างเท้าเท่าไหล่ ความสูงตามถนัด", sets: "Warm 12, Work 2RIR/1RIR/0.5RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Leg Extension", note: "เล่นช้า ขึ้นสุดลงสุด", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Abs Crunch Cable/Machine", note: "ใช้ V-bar หันหน้าเข้าเครื่อง", sets: "Feel 20, Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Leg Raise", note: "ห้อยตัว", sets: "15 reps x 5 sets", rest: "พักเซตละ 1 นาที" },
    ],
    home: [
      { name: "Dumbbell Shoulder Press", note: "เบาะ 80 องศา เอาศอกมาหน้าลำตัวนิดนึง", sets: "Feel 20, Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Dumbbell Front Raise", note: "แขวนได้นิดหน่อย โฟกัสลากศอกไปด้านหน้า", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Goblet Squat", note: "เท้ากว้างเท่าไหล่ ล็อคหลัง", sets: "Feel 20, Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Sumo Squat", note: "ยืดเท้ากว้าง เปิดปลายเท้าออก 45 องศา", sets: "Warm 12, Work 2RIR/1.5RIR/1RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Stiff Deadlift", note: "ล็อคหลัง ก้นกัน ล็อคเข่านิด", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Abs Crunch Cable/Machine", note: "ใช้ V-bar หันหน้าเข้าเครื่อง", sets: "Feel 20, Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Leg Raise", note: "ห้อยตัว", sets: "15 reps x 5 sets", rest: "พักเซตละ 1 นาที" },
    ],
  },
  day4: {
    title: "Day 4: Rest",
    emoji: "😴",
    color: "#7c7c9a",
    gym: [],
    home: [],
    restDay: true,
  },
  day5: {
    title: "Day 5: Upper",
    emoji: "🔝",
    color: "#EE5A24",
    gym: [
      { name: "Flat Smith Press", note: "บาร์ตำแหน่งแตะอกล่าง วางเท้าให้มั่น", sets: "Feel 20, Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Incline Smith Machine Press", note: "ม้านั่ง 30-40 องศา บาร์ตำแหน่งแตะอก", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Bar Lat Pulldown", note: "จับบาร์กว้างกว่าหัวไหล่ เอนหลังเล็กน้อย", sets: "Feel 20, Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "V-Grip Lat Pulldown", note: "เอนหลังเล็กน้อย แอ่นอก วางเท้าให้มั่น", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Preacher Curl หรือ Spider Curl", note: "ลอคหน้าลำตัว ออกแรงจากกล้ามแขน", sets: "Feel 20, Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Seated Dumbbell Curl หรือ Drag Curl", note: "ลอคหลังตรง ล็อคศอก", sets: "Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail/Drop 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Leg Raise", note: "ห้อยตัว", sets: "15 reps x 5 sets", rest: "พักเซตละ 1 นาที" },
    ],
    home: [
      { name: "วิดพื้นมือกว้าง หรือ Flat Dumbbell Press", note: "วางมือกว้างกว่าไหล่ จังหวะลง", sets: "วอร์ม เหลือแรง 50%, เซ็ต 1-5 เหลือแรง 2/1.5/1/0.5/วิดจนหมดแรง", rest: "พัก 3 นาที" },
      { name: "วิดพื้นอกบน หรือ Incline Dumbbell Press", note: "วางมือกว้างเท่าหุ่ฮ ล็อคหลังให้ตรง", sets: "วอร์ม เหลือแรง 50%, เซ็ต 1-5 เหลือแรง 2/1.5/1/0.5/วิดจนหมดแรง", rest: "พัก 3 นาที" },
      { name: "Band Lat Pulldown", note: "ยืนยึดยางไว้กับจุดสูง", sets: "Feel 20, Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "V-Grip Band Pulldown", note: "ใช้ยางยืดแทนเครื่อง วางท่าให้มั่น", sets: "Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Spider Curl หรือ Standing Curl", note: "ถอกหน้าลำตัว ออกแรงจากกล้ามแขน", sets: "Feel 20, Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Seated Dumbbell Curl หรือ Hammer Curl", note: "ลอคหลังตรง", sets: "Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail/Drop 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Leg Raise", note: "ห้อยตัว", sets: "15 reps x 5 sets", rest: "พักเซตละ 1 นาที" },
    ],
  },
  day6: {
    title: "Day 6: Shoulder",
    emoji: "🤸",
    color: "#a78bfa",
    gym: [
      { name: "Smith Shoulder Press", note: "เบาะ 80 องศา เอาศอกมาหน้าลำตัวนิดนึง", sets: "Feel 20, Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Rope Front Raise", note: "แขวนได้นิดหน่อย โฟกัสลากศอกไปด้านหน้า", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Lateral Raise", note: "เล่นเบา โฟกัสยกศอกขึ้นมาบนไหล่ข้าง", sets: "Warm Kg 20, Fail/Drop ครั้ง x 4 เซต", rest: "พัก 3 นาที" },
      { name: "Cable Rear Delt Fly", note: "นั่งหรือยืนก็ได้ ลากศอกออกด้านนอก", sets: "Warm Kg 20, Fail/Drop ครั้ง x 4 เซต", rest: "พัก 3 นาที" },
      { name: "Stiff Deadlift", note: "ล็อคหลัง ก้นกัน ล็อคเข่านิด", sets: "Feel 20, Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Super Set: Reverse + Bar Extension", note: "เล่น 2 ข้างพร้อมกัน", sets: "Feel 20, Warm 12, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 12 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Overhead Extension", note: "ใช้เชือกหรือบาร์ ล็อคศอกนิ่ง", sets: "Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail/Drop 15 ครั้ง", rest: "พัก 1 นาที" },
    ],
    home: [
      { name: "Dumbbell Shoulder Press", note: "เบาะ 80 องศา เอาศอกมาหน้าลำตัวนิดนึง", sets: "Feel 20, Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Dumbbell Front Raise", note: "แขวนได้นิดหน่อย โฟกัสลากศอกไปด้านหน้า", sets: "Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Lateral Raise", note: "เล่นเบา โฟกัสยกศอกขึ้นมาบนไหล่ข้าง", sets: "Warm Kg 20, Fail/Drop ครั้ง x 4 เซต", rest: "พัก 3 นาที" },
      { name: "Dumbbell Rear Delt Fly", note: "นั่งหรือยืนก็ได้ มือระดับสายตาตลอด", sets: "Warm Kg 20, Fail/Drop ครั้ง x 4 เซต", rest: "พัก 3 นาที" },
      { name: "Goblet Squat", note: "เท้ากว้างเท่าไหล่ ล็อคหลัง", sets: "Feel 20, Warm 12, Work 1.5RIR/1RIR/0.5RIR/Fail/Drop 12 ครั้ง", rest: "พัก 3 นาที" },
      { name: "Super Set: Skull Crusher + Kickback", note: "นอนกับม้าได้ไม่มีเบาะ", sets: "Feel 20, Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail 15 ครั้ง", rest: "พัก 2 นาที" },
      { name: "Dumbbell Overhead Extension", note: "ล็อคศอกตึง ลงให้สุดดันเบาแตะละบัก", sets: "Warm 15, Work 2RIR/1.5RIR/1RIR/0.5RIR/Fail/Drop 15 ครั้ง", rest: "พัก 1 นาที" },
    ],
  },
  day7: {
    title: "Day 7: Rest",
    emoji: "😴",
    color: "#7c7c9a",
    gym: [],
    home: [],
    restDay: true,
  },
};
